name: socioverse
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  material_design_icons_flutter: ^7.0.7296
  pinput: ^3.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_svg: ^2.0.7
  ionicons: ^0.2.2
  flutter_snake_navigationbar: ^0.6.1
  smooth_page_indicator: ^1.1.0
  autoscale_tabbarview: ^1.0.2
  flutter_map: ^5.0.0
  photo_manager:  ^3.0.0-dev.4
  photo_view: ^0.14.0
  shared_preferences: ^2.1.2
  http: ^1.1.0
  face_camera: ^0.0.8
  fluttertoast: ^8.2.2
  image_picker: ^1.0.4
  firebase_core: ^2.19.0
  firebase_storage: ^11.3.1
  image_cropper: ^5.0.0
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0
  flutter_spinkit: ^5.2.0
  loader_overlay: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  uuid: ^4.1.0
  cached_network_image: ^3.3.0
  flutter_launcher_icons: ^0.13.1
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.2.0
  story_view: ^0.16.0
  provider: ^6.1.1
  shimmer: ^3.0.0
  socket_io_client: ^2.0.3+1
  flutter_svg_provider: ^1.0.3
  debounce_throttle: ^2.0.0
  bottom_drawer: ^0.0.5
  recase: ^4.0.0
  lottie: ^3.1.0
  custom_sliding_segmented_control: ^1.8.1
  
flutter_icons:
 image_path: "assets/icon.png"
 android: true
 ios: true
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/Country_flag/
    - assets/lottie/
