name: socioverse
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  carousel_slider: ^4.2.1
  material_design_icons_flutter: ^7.0.7296
  pinput: ^2.2.31
  flutter_countdown_timer: ^4.1.0
  flutter_svg: ^2.0.7
  ionicons: ^0.2.2
  flutter_snake_navigationbar: ^0.6.1
  smooth_page_indicator: ^1.1.0
  story_view: ^0.15.0
  autoscale_tabbarview: ^1.0.2
  flutter_map: ^5.0.0
  photo_manager: ^2.7.1
  photo_view: ^0.14.0
  shared_preferences: ^2.1.2
  http: ^1.1.0
  # for being able to play videos
  video_player: ^2.6.1
  # provides controls for playing videos
  chewie: ^1.5.0
  face_camera: ^0.0.8
  fluttertoast: ^8.2.2
  image_picker: ^1.0.4
  firebase_core: ^2.19.0
  firebase_storage: ^11.3.1
  image_cropper: ^5.0.0
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0
  flutter_spinkit: ^5.2.0
  loader_overlay: ^2.3.2
  internet_connection_checker: ^1.0.0+1
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/Country_flag/
