// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClnRJAnrJgAgkYjuYnlvu-CJ6Cxyklebo',
    appId: '1:689574504641:web:a22f6a2fa343e4221acc40',
    messagingSenderId: '689574504641',
    projectId: 'socioverse-2025',
    authDomain: 'socioverse-2025.firebaseapp.com',
    storageBucket: 'socioverse-2025.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6jmRR2EHRotE68NPxrltD8UHJC3ZHOSE',
    appId: '1:689574504641:android:35eb8c823d2da7981acc40',
    messagingSenderId: '689574504641',
    projectId: 'socioverse-2025',
    storageBucket: 'socioverse-2025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7HJmCxdqaQvvJkHQ9hkMkVceN5Smli7E',
    appId: '1:689574504641:ios:619e0bb67910d8dc1acc40',
    messagingSenderId: '689574504641',
    projectId: 'socioverse-2025',
    storageBucket: 'socioverse-2025.appspot.com',
    iosBundleId: 'com.example.socioverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7HJmCxdqaQvvJkHQ9hkMkVceN5Smli7E',
    appId: '1:689574504641:ios:ac5cef7acfae9b7b1acc40',
    messagingSenderId: '689574504641',
    projectId: 'socioverse-2025',
    storageBucket: 'socioverse-2025.appspot.com',
    iosBundleId: 'com.example.socioverse.RunnerTests',
  );
}
